version: "3.9"
services:
    web:
        container_name: backendnet5
        build: .
        ports:
            - "5005:5000"
        depends_on:
            - database
    database:
        container_name: postgres
        image: postgres:latest
        ports: 
            - "5433:5433"
        environment:
            - POSTGRES_PASSWORD=admin
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql